import '../../App.css'


const dataset=[
    [
      "Datasets/captcha_images_v2/5dxnm.png",
      "5dxnm"
   ],
    [
      "Datasets/captcha_images_v2/gnbde.png",
      "gnbde"
   ],
    [
      "Datasets/captcha_images_v2/c2fb7.png",
      "c2fb7"
   ],
    [
      "Datasets/captcha_images_v2/8npe3.png",
      "8npe3"
   ],
    [
      "Datasets/captcha_images_v2/c7gb3.png",
      "c7gb3"
   ],
    [
      "Datasets/captcha_images_v2/mx8bb.png",
      "mx8bb"
   ],
    [
      "Datasets/captcha_images_v2/men4f.png",
      "men4f"
   ],
    [
      "Datasets/captcha_images_v2/n6xc5.png",
      "n6xc5"
   ],
    [
      "Datasets/captcha_images_v2/enn7n.png",
      "enn7n"
   ],
    [
      "Datasets/captcha_images_v2/d22n7.png",
      "d22n7"
   ],
    [
      "Datasets/captcha_images_v2/74eyg.png",
      "74eyg"
   ],
    [
      "Datasets/captcha_images_v2/ydg8n.png",
      "ydg8n"
   ],
    [
      "Datasets/captcha_images_v2/gf2g4.png",
      "gf2g4"
   ],
    [
      "Datasets/captcha_images_v2/378e5.png",
      "3.78E+07"
   ],
    [
      "Datasets/captcha_images_v2/d236n.png",
      "d236n"
   ],
    [
      "Datasets/captcha_images_v2/p2ym2.png",
      "p2ym2"
   ],
    [
      "Datasets/captcha_images_v2/5n3w4.png",
      "5n3w4"
   ],
    [
      "Datasets/captcha_images_v2/f6ww8.png",
      "f6ww8"
   ],
    [
      "Datasets/captcha_images_v2/2wx73.png",
      "2wx73"
   ],
    [
      "Datasets/captcha_images_v2/m5meg.png",
      "m5meg"
   ],
    [
      "Datasets/captcha_images_v2/xwx7d.png",
      "xwx7d"
   ],
    [
      "Datasets/captcha_images_v2/7634y.png",
      "7634y"
   ],
    [
      "Datasets/captcha_images_v2/nmy2x.png",
      "nmy2x"
   ],
    [
      "Datasets/captcha_images_v2/ppwyd.png",
      "ppwyd"
   ],
    [
      "Datasets/captcha_images_v2/yf347.png",
      "yf347"
   ],
    [
      "Datasets/captcha_images_v2/ewnx8.png",
      "ewnx8"
   ],
    [
      "Datasets/captcha_images_v2/325fb.png",
      "325fb"
   ],
    [
      "Datasets/captcha_images_v2/7wnpm.png",
      "7wnpm"
   ],
    [
      "Datasets/captcha_images_v2/4nnf3.png",
      "4nnf3"
   ],
    [
      "Datasets/captcha_images_v2/77387.png",
      "77387"
   ],
    [
      "Datasets/captcha_images_v2/xnnc3.png",
      "xnnc3"
   ],
    [
      "Datasets/captcha_images_v2/xbem6.png",
      "xbem6"
   ],
    [
      "Datasets/captcha_images_v2/mdyp7.png",
      "mdyp7"
   ],
    [
      "Datasets/captcha_images_v2/47m2b.png",
      "47m2b"
   ],
    [
      "Datasets/captcha_images_v2/ndecc.png",
      "ndecc"
   ],
    [
      "Datasets/captcha_images_v2/n5w5g.png",
      "n5w5g"
   ],
    [
      "Datasets/captcha_images_v2/32cnn.png",
      "32cnn"
   ],
    [
      "Datasets/captcha_images_v2/y53c2.png",
      "y53c2"
   ],
    [
      "Datasets/captcha_images_v2/bdg84.png",
      "bdg84"
   ],
    [
      "Datasets/captcha_images_v2/ccn2x.png",
      "ccn2x"
   ],
    [
      "Datasets/captcha_images_v2/2n73f.png",
      "2n73f"
   ],
    [
      "Datasets/captcha_images_v2/m4g8g.png",
      "m4g8g"
   ],
    [
      "Datasets/captcha_images_v2/36bc2.png",
      "36bc2"
   ],
    [
      "Datasets/captcha_images_v2/p4pde.png",
      "p4pde"
   ],
    [
      "Datasets/captcha_images_v2/excmn.png",
      "excmn"
   ],
    [
      "Datasets/captcha_images_v2/ef4np.png",
      "ef4np"
   ],
    [
      "Datasets/captcha_images_v2/x3deb.png",
      "x3deb"
   ],
    [
      "Datasets/captcha_images_v2/4exnn.png",
      "4exnn"
   ],
    [
      "Datasets/captcha_images_v2/pwmbn.png",
      "pwmbn"
   ],
    [
      "Datasets/captcha_images_v2/efe62.png",
      "efe62"
   ],
    [
      "Datasets/captcha_images_v2/mpmy5.png",
      "mpmy5"
   ],
    [
      "Datasets/captcha_images_v2/nb267.png",
      "nb267"
   ],
    [
      "Datasets/captcha_images_v2/cdcb3.png",
      "cdcb3"
   ],
    [
      "Datasets/captcha_images_v2/f2m8n.png",
      "f2m8n"
   ],
    [
      "Datasets/captcha_images_v2/3n2b4.png",
      "3n2b4"
   ],
    [
      "Datasets/captcha_images_v2/7xcyd.png",
      "7xcyd"
   ],
    [
      "Datasets/captcha_images_v2/24f6w.png",
      "24f6w"
   ],
    [
      "Datasets/captcha_images_v2/2en7g.png",
      "2en7g"
   ],
    [
      "Datasets/captcha_images_v2/n8ydd.png",
      "n8ydd"
   ],
    [
      "Datasets/captcha_images_v2/6n5fd.png",
      "6n5fd"
   ],
    [
      "Datasets/captcha_images_v2/pme86.png",
      "pme86"
   ],
    [
      "Datasets/captcha_images_v2/ncw4g.png",
      "ncw4g"
   ],
    [
      "Datasets/captcha_images_v2/7fde7.png",
      "7fde7"
   ],
    [
      "Datasets/captcha_images_v2/56c34.png",
      "56c34"
   ],
    [
      "Datasets/captcha_images_v2/wddcp.png",
      "wddcp"
   ],
    [
      "Datasets/captcha_images_v2/73mnx.png",
      "73mnx"
   ],
    [
      "Datasets/captcha_images_v2/664nf.png",
      "664nf"
   ],
    [
      "Datasets/captcha_images_v2/xnfx5.png",
      "xnfx5"
   ],
    [
      "Datasets/captcha_images_v2/mmc5n.png",
      "mmc5n"
   ],
    [
      "Datasets/captcha_images_v2/wc2bd.png",
      "wc2bd"
   ],
    [
      "Datasets/captcha_images_v2/2w4y7.png",
      "2w4y7"
   ],
    [
      "Datasets/captcha_images_v2/wnmyn.png",
      "wnmyn"
   ],
    [
      "Datasets/captcha_images_v2/44fyb.png",
      "44fyb"
   ],
    [
      "Datasets/captcha_images_v2/myc3c.png",
      "myc3c"
   ],
    [
      "Datasets/captcha_images_v2/6end3.png",
      "6end3"
   ],
    [
      "Datasets/captcha_images_v2/gymmn.png",
      "gymmn"
   ],
    [
      "Datasets/captcha_images_v2/4egem.png",
      "4egem"
   ],
    [
      "Datasets/captcha_images_v2/78eec.png",
      "78eec"
   ],
    [
      "Datasets/captcha_images_v2/7m8px.png",
      "7m8px"
   ],
    [
      "Datasets/captcha_images_v2/w6pxy.png",
      "w6pxy"
   ],
    [
      "Datasets/captcha_images_v2/63824.png",
      "63824"
   ],
    [
      "Datasets/captcha_images_v2/ng756.png",
      "ng756"
   ],
    [
      "Datasets/captcha_images_v2/5ywwf.png",
      "5ywwf"
   ],
    [
      "Datasets/captcha_images_v2/pn7pn.png",
      "pn7pn"
   ],
    [
      "Datasets/captcha_images_v2/bmxpe.png",
      "bmxpe"
   ],
    [
      "Datasets/captcha_images_v2/d4n82.png",
      "d4n82"
   ],
    [
      "Datasets/captcha_images_v2/b4d7c.png",
      "b4d7c"
   ],
    [
      "Datasets/captcha_images_v2/xgcxy.png",
      "xgcxy"
   ],
    [
      "Datasets/captcha_images_v2/bnc5f.png",
      "bnc5f"
   ],
    [
      "Datasets/captcha_images_v2/nwncn.png",
      "nwncn"
   ],
    [
      "Datasets/captcha_images_v2/3cpwb.png",
      "3cpwb"
   ],
    [
      "Datasets/captcha_images_v2/gnf85.png",
      "gnf85"
   ],
    [
      "Datasets/captcha_images_v2/e7nx4.png",
      "e7nx4"
   ],
    [
      "Datasets/captcha_images_v2/573bn.png",
      "573bn"
   ],
    [
      "Datasets/captcha_images_v2/n4cpy.png",
      "n4cpy"
   ],
    [
      "Datasets/captcha_images_v2/3p67n.png",
      "3p67n"
   ],
    [
      "Datasets/captcha_images_v2/c353e.png",
      "c353e"
   ],
    [
      "Datasets/captcha_images_v2/53wb8.png",
      "53wb8"
   ],
    [
      "Datasets/captcha_images_v2/yf28d.png",
      "yf28d"
   ],
    [
      "Datasets/captcha_images_v2/cnex4.png",
      "cnex4"
   ],
    [
      "Datasets/captcha_images_v2/gcfgp.png",
      "gcfgp"
   ],
    [
      "Datasets/captcha_images_v2/445cc.png",
      "445cc"
   ],
    [
      "Datasets/captcha_images_v2/55w5c.png",
      "55w5c"
   ],
    [
      "Datasets/captcha_images_v2/y2xg4.png",
      "y2xg4"
   ]
]
export default dataset;